apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: hackazon-hostrule
spec:
  virtualhost:
    fqdn: hackazon-07.tkg-lab.livefire.lab # mandatory, change XX with your mduser number!
    enableVirtualHost: true
    # gslb:
      # fqdn: vip1.global.avi.com
    # wafPolicy: System-WAF-Policy
    tls:
      sslKeyCertificate:
        name: livefire # custom certificate to be used
        type: ref
      sslProfile: System-Standard
      termination: edge
